### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by tiesmaster** [skoonhoven/issue-receipt-printer#2]
As mentioned in PR #1: thanks for the project. However, I ran into the following problem: I think the embedded icons are missing.

I've managed to get the project to retrieve the Jira ticket, but when printing, I get a `Value of 'null' is not valid for 'stream'.`, with the following stacktrace:

> StackTrace:
>        at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
>        at System.Drawing.Image.FromStream(Stream stream)
>        at IssuePrinter.Core.Helpers.IssueFormattingHelper.OpenEmbeddedImage(String resourceName) in C:\Users\Thijs Brobbel\src\playground\issue-receipt-printer\src\IssuePrinter.Core\Helpers\IssueFormattingHelper.cs:line 68

Looking at that method, that tells me that the icons weren't committed to source control, and hence missing. Could you maybe add them?

**Comment by skoonhoven** [comment]
Hi @tiesmaster,

Thnx for trying out the issue printer outside of our office. I have added the missing icons. 

Looking forward to hear if it works out for you!

**Comment by tiesmaster** [comment]
Awesome!! I'll try it out tomorrow morning.
